import attr


@attr.s
class GoszakupCompanyRow:
    pid = attr.ib(default='')
    bin = attr.ib(default='')
    iin = attr.ib(default='')
    inn = attr.ib(default='')
    unp = attr.ib(default='')
    regdate = attr.ib(default='')
    crdate = attr.ib(default='')
    number_reg = attr.ib(default='')
    series = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')
    email = attr.ib(default='')
    phone = attr.ib(default='')
    website = attr.ib(default='')
    last_update_date = attr.ib(default='')
    country_code = attr.ib(default='')
    qvazi = attr.ib(default='')
    customer = attr.ib(default='')
    organizer = attr.ib(default='')
    mark_national_company = attr.ib(default='')
    ref_kopf_code = attr.ib(default='')
    mark_assoc_with_disab = attr.ib(default='')
    year = attr.ib(default='')
    mark_resident = attr.ib(default='')
    system_id = attr.ib(default='')
    supplier = attr.ib(default='')
    krp_code = attr.ib(default='')
    oked_list = attr.ib(default='')
    kse_code = attr.ib(default='')
    mark_world_company = attr.ib(default='')
    mark_state_monopoly = attr.ib(default='')
    mark_natural_monopoly = attr.ib(default='')
    mark_patronymic_producer = attr.ib(default='')
    mark_patronymic_supplyer = attr.ib(default='')
    mark_small_employer = attr.ib(default='')
    type_supplier = attr.ib(default='')
    is_single_org = attr.ib(default='')
    index_date = attr.ib(default='')


@attr.s
class GoszakupContractRow:
    id = attr.ib(default='')
    parent_id = attr.ib(default='')
    root_id = attr.ib(default='')
    trd_buy_id = attr.ib(default='')
    trd_buy_number_anno = attr.ib(default='')
    trd_buy_name_ru = attr.ib(default='')
    trd_buy_name_kz = attr.ib(default='')
    ref_contract_status_id = attr.ib(default='')
    deleted = attr.ib(default='')
    crdate = attr.ib(default='')
    last_update_date = attr.ib(default='')
    supplier_id = attr.ib(default='')
    supplier_biin = attr.ib(default='')
    supplier_bik = attr.ib(default='')
    supplier_iik = attr.ib(default='')
    supplier_bank_name_kz = attr.ib(default='')
    supplier_bank_name_ru = attr.ib(default='')
    supplier_legal_address = attr.ib(default='')
    supplier_bill_id = attr.ib(default='')
    contract_number = attr.ib(default='')
    sign_reason_doc_name = attr.ib(default='')
    sign_reason_doc_date = attr.ib(default='')
    trd_buy_itogi_date_public = attr.ib(default='')
    customer_id = attr.ib(default='')
    customer_bin = attr.ib(default='')
    customer_bik = attr.ib(default='')
    customer_iik = attr.ib(default='')
    customer_bill_id = attr.ib(default='')
    customer_bank_name_kz = attr.ib(default='')
    customer_bank_name_ru = attr.ib(default='')
    customer_legal_address = attr.ib(default='')
    contract_number_sys = attr.ib(default='')
    payments_terms_ru = attr.ib(default='')
    payments_terms_kz = attr.ib(default='')
    ref_subject_type_id = attr.ib(default='')
    ref_subject_types_id = attr.ib(default='')
    is_gu = attr.ib(default='') # integer
    fin_year = attr.ib(default='') # integer
    ref_contract_agr_form_id = attr.ib(default='')
    ref_contract_year_type_id = attr.ib(default='')
    ref_finsource_id = attr.ib(default='')
    ref_currency_code = attr.ib(default='')
    exchange_rate = attr.ib(default='')
    contract_sum = attr.ib(default='')
    contract_sum_wnds = attr.ib(default='')
    sign_date = attr.ib(default='')
    ec_end_date = attr.ib(default='')
    plan_exec_date = attr.ib(default='')
    fakt_exec_date = attr.ib(default='')
    fakt_sum = attr.ib(default='')
    fakt_sum_wnds = attr.ib(default='')
    contract_end_date = attr.ib(default='')
    ref_contract_cancel_id = attr.ib(default='')
    ref_contract_type_id = attr.ib(default='')
    description_kz = attr.ib(default='')
    description_ru = attr.ib(default='')
    fakt_trade_methods_id = attr.ib(default='')
    ec_customer_approve = attr.ib(default='')
    ec_supplier_approve = attr.ib(default='')
    contract_ms = attr.ib(default='')
    treasure_req_num = attr.ib(default='')
    treasure_req_date = attr.ib(default='')
    treasure_not_num = attr.ib(default='')
    treasure_not_date = attr.ib(default='')
    system_id = attr.ib(default='')
    index_date = attr.ib(default='')


@attr.s
class GoszakupUntrustedSupplierRow:
    pid = attr.ib(default='')
    supplier_biin = attr.ib(default='')
    supplier_innunp = attr.ib(default='')
    supplier_name_ru = attr.ib(default='')
    supplier_name_kz = attr.ib(default='')
    kato_list = attr.ib(default='')
    index_date = attr.ib(default='')
    system_id = attr.ib(default='')


@attr.s
class GoszakupContractTypeRow:
    id = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')


@attr.s
class GoszakupContractStatusRow:
    id = attr.ib(default='')
    code = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')


@attr.s
class GoszakupTenderMethodRow:
    code = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')
    is_active = attr.ib(default='')
    type = attr.ib(default='')
    symbol_code = attr.ib(default='')
    f1 = attr.ib(default='')
    ord = attr.ib(default='')
    f2 = attr.ib(default='')
    id = attr.ib(default='')


@attr.s
class GoszakupLotsStatusRow:
    id = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')
    code = attr.ib(default='')


@attr.s
class GoszakupBuyStatusRow:
    id = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')
    code = attr.ib(default='')


@attr.s
class GoszakupLotsRow:
    id = attr.ib(default='')
    lot_number = attr.ib(default='')
    ref_lot_status_id = attr.ib(default='')
    last_update_date = attr.ib(default='')
    union_lots = attr.ib(default='')
    count = attr.ib(default='')
    amount = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')
    description_ru = attr.ib(default='')
    description_kz = attr.ib(default='')
    customer_id = attr.ib(default='')
    customer_bin = attr.ib(default='')
    trd_buy_number_anno = attr.ib(default='')
    trd_buy_id = attr.ib(default='')
    dumping = attr.ib(default='')
    dumping_lot_price = attr.ib(default='')
    psd_sign = attr.ib(default='')
    consulting_services = attr.ib(default='')
    point_list = attr.ib(default='')
    singl_org_sign = attr.ib(default='')
    is_light_industry = attr.ib(default='')
    is_construction_work = attr.ib(default='')
    disable_person_id = attr.ib(default='')
    customer_name_kz = attr.ib(default='')
    customer_name_ru = attr.ib(default='')
    ref_trade_methods_id = attr.ib(default='')
    index_date = attr.ib(default='')
    system_id = attr.ib(default='')


@attr.s
class GoszakupTradeBuyRow:
    id = attr.ib(default='')
    number_anno = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')
    total_sum  = attr.ib(default='')
    count_lots = attr.ib(default='')
    ref_trade_methods_id = attr.ib(default='')
    ref_subject_type_id = attr.ib(default='')
    customer_bin = attr.ib(default='')
    customer_pid = attr.ib(default='')
    org_bin = attr.ib(default='')
    org_pid = attr.ib(default='')
    ref_buy_status_id = attr.ib(default='')
    start_date = attr.ib(default='')
    repeat_start_date = attr.ib(default='')
    repeat_end_date = attr.ib(default='')
    end_date = attr.ib(default='')
    publish_date = attr.ib(default='')
    itogi_date_public = attr.ib(default='')
    ref_type_trade_id = attr.ib(default='')
    disable_person_id = attr.ib(default='')
    discus_start_date = attr.ib(default='')
    discus_end_date = attr.ib(default='')
    id_supplier = attr.ib(default='')
    biin_supplier = attr.ib(default='')
    parent_id = attr.ib(default='')
    singl_org_sign = attr.ib(default='')
    is_light_industry = attr.ib(default='')
    is_construction_work = attr.ib(default='')
    customer_name_kz = attr.ib(default='')
    customer_name_ru = attr.ib(default='')
    org_name_kz = attr.ib(default='')
    org_name_ru = attr.ib(default='')
    system_id = attr.ib(default='')
    index_date = attr.ib(default='')


@attr.s
class GoszakupPlanRow:
    pid = attr.ib(default='')
    bin = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')
    doc_count = attr.ib(default='')


@attr.s
class GoszakupPlanPointRow:
    id = attr.ib(default='')
    rootrecord_id = attr.ib(default='')
    sys_subjects_id = attr.ib(default='')
    sys_organizator_id = attr.ib(default='')
    subject_biin = attr.ib(default='')
    subject_name_ru = attr.ib(default='')
    subject_name_kz = attr.ib(default='')
    name_ru = attr.ib(default='')
    name_kz = attr.ib(default='')
    ref_trade_methods_id = attr.ib(default='')
    ref_units_code = attr.ib(default='')
    count = attr.ib(default='')
    price = attr.ib(default='')
    amount = attr.ib(default='')
    ref_months_id = attr.ib(default='')
    ref_pln_point_status_id = attr.ib(default='')
    pln_point_year = attr.ib(default='')
    ref_subject_type_id = attr.ib(default='')
    ref_enstru_code = attr.ib(default='')
    ref_finsource_id = attr.ib(default='')
    ref_abp_code = attr.ib(default='')
    is_qvazi = attr.ib(default='')
    date_create = attr.ib(default='')
    timestamp = attr.ib(default='')
    ref_point_type_id = attr.ib(default='')
    desc_ru = attr.ib(default='')
    desc_kz = attr.ib(default='')
    extra_desc_kz = attr.ib(default='')
    extra_desc_ru = attr.ib(default='')
    sum_1 = attr.ib(default='')
    sum_2 = attr.ib(default='')
    sum_3 = attr.ib(default='')
    supply_date_ru = attr.ib(default='')
    prepayment = attr.ib(default='')
    ref_justification_id = attr.ib(default='')
    ref_amendment_agreem_type_id = attr.ib(default='')
    ref_amendm_agreem_justif_id = attr.ib(default='')
    contract_prev_point_id = attr.ib(default='')
    disable_person_id = attr.ib(default='')
    transfer_sys_subjects_id = attr.ib(default='')
    transfer_type = attr.ib(default='')
    ref_budget_type_id = attr.ib(default='')
    createdin_act_id = attr.ib(default='')
    is_active = attr.ib(default='')
    active_act_id = attr.ib(default='')
    is_deleted = attr.ib(default='')
    system_id = attr.ib(default='')
    index_date = attr.ib(default='')
    plan_act_id = attr.ib(default='')
    plan_act_number = attr.ib(default='')
    ref_plan_status_id = attr.ib(default='')
    plan_fin_year = attr.ib(default='')
    plan_preliminary = attr.ib(default='')
    date_approved = attr.ib(default='')


@attr.s
class GoszakupPlanKatoRow:
    id = attr.ib(default='')
    pln_points_id = attr.ib(default='')
    ref_kato_code = attr.ib(default='')
    ref_countries_code = attr.ib(default='')
    full_delivery_place_name_ru = attr.ib(default='')
    full_delivery_place_name_kz = attr.ib(default='')
    count = attr.ib(default='')
    is_active = attr.ib(default='')
    is_deleted = attr.ib(default='')
    system_id = attr.ib(default='')
    index_date = attr.ib(default='')


@attr.s
class GoszakupUntrustedSupplierRow:
    pid = attr.ib(default='')
    supplier_biin = attr.ib(default='')
    supplier_innunp = attr.ib(default='')
    supplier_name_ru = attr.ib(default='')
    supplier_name_kz = attr.ib(default='')
    kato_list = attr.ib(default='')
    index_date = attr.ib(default='')
    system_id = attr.ib(default='')


