
from attrs import define, field


@define
class SamrukSupplierRow:
    id = field(default='')
    identifier = field(default='')
    name_kk = field(default='')
    name_ru = field(default='')
    country_id = field(default='')
    begin_date = field(default='')
    end_date = field(default='')
    first_name = field(default='')
    iin = field(default='')
    last_name = field(default='')
    middle_name = field(default='')
    company_id = field(default='')
    position_kk = field(default='')
    position_ru = field(default='')
    email = field(default='')
    fax = field(default='')
    full_name_kk = field(default='')
    full_name_ru = field(default='')
    phone = field(default='')
    site = field(default='')
    building = field(default='')
    city = field(default='')
    flat = field(default='')
    postcode = field(default='')
    street = field(default='')
    kato_id = field(default='')


@define
class SamrukPurchaseRow:
    id = field(default='')
    row_number = field(default='')
    plan_id = field(default='')
    plan_item_group_id = field(default='')
    count = field(default='')
    price = field(default='')
    ext_id = field(default='')
    lot_id = field(default='')
    advert_id = field(default='')
    lot_count = field(default='')
    lot_price = field(default='')
    lot_sum_tru_nds = field(default='')
    lot_sum_tru_no_nds = field(default='')
    number = field(default='')
    acceptance_begin_date_time = field(default='')
    acceptance_end_date_time = field(default='')
    name_ru = field(default='')
    advert_tender_priority = field(default='')
    jhi_comment = field(default='')
    status = field(default='')
    status_date_time = field(default='')
    company_id = field(default='')
    sum = field(default='')
    advert_status = field(default='')


@define
class SamrukKztContractRow:
    id = field(default='')
    contract_id = field(default='')
    created_date = field(default='')
    contract_date_time = field(default='')
    contract_number = field(default='')
    control_date_time = field(default='')
    foreign_sum = field(default='')
    sum_nds = field(default='')
    sum_no_nds = field(default='')
    tender_type = field(default='')
    currency_id = field(default='')
    advert_id = field(default='')
    flag_paper_contract = field(default='')
    nds_size_id = field(default='')
    contract_items_name_kk = field(default='')
    contract_items_name_ru = field(default='')
    local_content_projected_share = field(default='')
    contract_type = field(default='')
    prev_contract_card_id = field(default='')
    main_contract_card_id = field(default='')
    system_number = field(default='')
    last_contract_card_id = field(default='')
    rescission_date_time = field(default='')
    rescission_type = field(default='')
    currency_rate_id = field(default='')
    currency_date = field(default='')
    flag_nds_lot = field(default='')
    jhi_comment = field(default='')
    status = field(default='')
    id_supplier = field(default='')
    id_customer = field(default='')
    supplier_bik = field(default='')
    supplier_add_req = field(default='')
    supplier_iik = field(default='')
    supplier_bank_name_ru = field(default='')


@define
class SamrukBadSupplierRow:
    bin_iin = field(default='')
    name_ru = field(default='')
    full_name_ru = field(default='')
    reason_ru = field(default='')
    created_date = field(default='')
    start_date = field(default='')
    end_date = field(default='')


@define
class SamrukKztPlanRow:
    id = field(default='')
    year = field(default='')
    type = field(default='')
    durationtype = field(default='')
    itemcount = field(default='')
    approvedplansum = field(default='')


@define
class SamrukKztContractSubjectsRow:
    id = field(default='')
    count = field(default='')
    execution_sum_nds = field(default='')
    execution_sum_no_nds = field(default='')
    foreign_price = field(default='')
    foreign_sum = field(default='')
    sum_nds = field(default='')
    sum_no_nds = field(default='')
    contract_card_id = field(default='')
    lot_id = field(default='')
    plan_item_id = field(default='')
    price = field(default='')
    country_id = field(default='')
    prev_contract_item_id = field(default='')
    delivery_date_time = field(default='')
    final_payment = field(default='')
    interim_payment = field(default='')
    prepayment = field(default='')
    detail_ru = field(default='')
    nds_size_id = field(default='')
    local_content = field(default='')
    execution_count = field(default='')
    stkz_certificate_position_id = field(default='')
    local_content_projected_share = field(default='')
    foreign_execution_sum = field(default='')
    jhi_comment = field(default='')
    status = field(default='')
    year_count = field(default='')
    foreign_price_year = field(default='')
    foreign_sum_year = field(default='')
    price_year = field(default='')
    jhi_year = field(default='')
    sum_nds_year = field(default='')
    sum_no_nds_year = field(default='')


@define
class SamrukKztPlanItemRow:
    id = field(default='')
    planid = field(default='')
    tenderpriority = field(default='')
    rownumber = field(default='')
    extid = field(default='')
    tendersubjecttype = field(default='')
    mkeicode = field(default='')
    price = field(default='')
    priceconfidenceto = field(default='')
    priceaverage = field(default='')
    prevpriceconfidenceto = field(default='')
    prevpriceaverage = field(default='')
    priceexceeded = field(default='')
    count = field(default='')
    sumtrunonds = field(default='')
    sumtrunds = field(default='')
    tendertype = field(default='')
    localcontent = field(default='')
    katocode = field(default='')
    tenderlocation = field(default='')
    durationmonth = field(default='')
    incotermsconditioncode = field(default='')
    deliverycountrycode = field(default='')
    deliverylocation = field(default='')
    deliverykatocode = field(default='')
    deleted = field(default='')
    hidden = field(default='')
    nonds = field(default='')
    transienttender = field(default='')
    trucode = field(default='')
    organizerbin = field(default='')
    subdivision = field(default='')
    sort = field(default='')
    addattributeru = field(default='')
    addattributekk = field(default='')
    singlesourcereason = field(default='')
    createddate = field(default='')
    createduser = field(default='')
    lastmodifieddate = field(default='')
    lastmodifieduser = field(default='')
    executioncount = field(default='')
    executionsumnonds = field(default='')
    prevcontractcardstatushistory = field(default='')
    contractcardtype = field(default='')
    checkedskb = field(default='')


@define
class SamrukCertRow:
    id = field(default='')
    bin = field(default='')
    certificate_id = field(default='')
    description_kk = field(default='')
    description_ru = field(default='')
    director_name_kk = field(default='')
    director_name_ru = field(default='')
    expiration_date = field(default='')
    issue_date = field(default='')
    kato_code = field(default='')
    modified_date = field(default='')
    name_kk = field(default='')
    name_ru = field(default='')
    jhi_number = field(default='')
    organization_code = field(default='')
    series = field(default='')
    id_stkz_certificate_position = field(default='')
    box_type = field(default='')
    count = field(default='')
    percent = field(default='')
    tnved = field(default='')
    unit_code = field(default='')
    description_kk_stkz_certificate_position = field(default='')
    description_ru_stkz_certificate_position = field(default='')


@define
class SamrukDictRow:
    id = field(default='')
    created_date = field(default='')
    code = field(default='')
    en = field(default='')
    ru = field(default='')
    kk = field(default='')
    version = field(default='')


@define
class SamrukParticipationLotRow:
    id = field(default='')
    finish_date = field(default='')
    bin_iin = field(default='')
    price = field(default='')
