query getContractUnits($from: String, $to: String, $limit: Int, $after: Int){
      Contract(filter: {lastUpdateDate: [$from, $to]}, limit: $limit, after: $after) {
        contract_id: id
        _: ContractUnits{
            id
            lot_id: lotId
            pln_point_id: plnPointId
            item_price: itemPrice
            item_price_wnds: itemPriceWnds
            quantity
            total_sum: totalSum
            total_sum_wnds: totalSumWnds
            fact_sum: factSum
            fact_sum_wnds: factSumWnds
            ks_proc: ksProc
            ks_sum: ksSum
            deleted
            trd_buy_id: trdBuyId
            contract_registry_id: contractRegistryId
            crdate
            exec_fakt_date: execFaktDate
            exec_plan_date: execPlanDate
            executed
            parent_id: parentId
            root_id: rootId
            ref_contract_status_id: refContractStatusId
            cr_deleted: crDeleted
            ref_amendm_agreem_justif_id: refAmendmAgreemJustifId
            system_id: systemId
            index_date: indexDate
        }
    }
}