query getPlanPoints($from: String, $to: String, $limit: Int, $after: Int){
          Plans(filter: {timestamp: [$from, $to]}, limit: $limit, after: $after) {
            id
            rootrecord_id: rootrecordId
            sys_subjects_id: sysSubjectsId
            sys_organizator_id: sysOrganizatorId
            subject_biin: subjectBiin
            subject_name_ru: subjectNameRu
            subject_name_kz: subjectNameKz
            name_ru: nameRu
            name_kz: nameKz
            ref_trade_methods_id: refTradeMethodsId
            ref_units_code: refUnitsCode
            count
            price
            amount
            ref_months_id: refMonthsId
            ref_pln_point_status_id: refPlnPointStatusId
            pln_point_year: plnPointYear
            ref_subject_type_id: refSubjectTypeId
            ref_enstru_code: refEnstruCode
            ref_finsource_id: refFinsourceId
            ref_abp_code: refAbpCode
            is_qvazi: isQvazi
            date_create: dateCreate
            timestamp: timestamp
            ref_point_type_id: refPointTypeId
            desc_ru: descRu
            desc_kz: descKz
            extra_desc_kz: extraDescKz
            extra_desc_ru: extraDescRu
            sum_1: sum1
            sum_2: sum2
            sum_3: sum3
            supply_date_ru: supplyDateRu
            prepayment: prepayment
            ref_justification_id: refJustificationId
            ref_amendment_agreem_type_id: refAmendmentAgreemTypeId
            ref_amendm_agreem_justif_id: refAmendmAgreemJustifId
            contract_prev_point_id: contractPrevPointId
            disable_person_id: disablePersonId
            transfer_sys_subjects_id: transferSysSubjectsId
            transfer_type: transferType
            ref_budget_type_id: refBudgetTypeId
            createdin_act_id: createdinActId
            is_active: isActive
            active_act_id: activeActId
            is_deleted: isDeleted
            system_id: systemId
            index_date: indexDate
            _: PlanActs{
                plan_act_id: id
                number: planActNumber
                ref_plan_status_id: refPlanStatusId
                plan_fin_year: planFinYear
                plan_preliminary: planPreliminary
                date_approved: dateApproved
            }
          }
        }